[package]
name = "rust-greedy-coin-microservice"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7.4"
tokio = { version = "1.36.0", features = ["full"] }
tower = "0.4.13"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"